# Theory of Complex Vector Spaces
Complex vector spaces extend the idea of real vector spaces by allowing vectors to have complex numbers as their components. In these spaces, vectors can be added together and multiplied by complex scalars to produce new vectors. Key operations in complex vector spaces include vector addition, scalar multiplication, vector negation, and complex conjugation.

# Creating complex column vectors

In [ ]:
import numpy as np

# Define a 2x2 square matrix
matrix = np.array([[2, 3],
                   [1, 4]])

# Define a vector of size 2
vector = np.array([5, 6])

# Multiply the matrix by the vector
result = np.dot(matrix, vector)

# Display the result
print("Matrix:\n", matrix)
print("\nVector:\n", vector)
print("\nResult of multiplication:\n", result)


## Manipulating Complex Column Vectors using NumPy
Here we demonstrate how to manipulate complex column vectors using NumPy, including operations like sum, negation, multiplication by a scalar, transpose, adjunct, and conjugate.

In [1]:

import numpy as np

# Define two complex column vectors
v1 = np.array([[2+3j], [5-4j], [1+1j]])
v2 = np.array([[1-1j], [3+2j], [4-4j]])

# Sum
sum_v = v1 + v2

# Negation
neg_v1 = -v1

# Multiplication by a scalar
scalar = 2 + 1j
mult_v1 = v1 * scalar

# Transpose
transpose_v1 = v1.T

# Adjunct (Conjugate transpose)
adjunct_v1 = v1.T.conj()

# Conjugate
conjugate_v1 = np.conjugate(v1)

(sum_v, neg_v1, mult_v1, transpose_v1, adjunct_v1, conjugate_v1)


(array([[3.+2.j],
        [8.-2.j],
        [5.-3.j]]),
 array([[-2.-3.j],
        [-5.+4.j],
        [-1.-1.j]]),
 array([[ 1.+8.j],
        [14.-3.j],
        [ 1.+3.j]]),
 array([[2.+3.j, 5.-4.j, 1.+1.j]]),
 array([[2.-3.j, 5.+4.j, 1.-1.j]]),
 array([[2.-3.j],
        [5.+4.j],
        [1.-1.j]]))

# Theory of Vector Spaces using Matrices
In the context of matrices, vector spaces can be defined where each vector is a matrix of a particular size. Operations on these matrix-vector spaces include matrix addition, scalar multiplication, matrix negation, transpose, adjunct, and conjugate. In this section, we focus on square matrices of size 3x3.

## Manipulating Square Matrices using NumPy
Examples of how to manipulate 3x3 square matrices using NumPy, showing operations such as sum, negation, multiplication by a scalar, conjugate, transpose, and adjunct.

In [ ]:

# Define two 3x3 complex matrices
m1 = np.array([[2+3j, 4-1j, 0], 
               [1+1j, 3+3j, 5], 
               [4, 6-2j, 1-1j]])
m2 = np.array([[1, 2+1j, 3-3j], 
               [0, -1+2j, 1-2j], 
               [3+3j, 2, 4+4j]])

# Sum
sum_m = m1 + m2

# Negation
neg_m1 = -m1

# Multiplication by a scalar
scalar = 0.5 + 0.5j
mult_m1 = m1 * scalar

# Conjugate
conjugate_m1 = np.conjugate(m1)

# Transpose
transpose_m1 = m1.T

# Adjunct (Conjugate transpose)
adjunct_m1 = m1.T.conj()

(sum_m, neg_m1, mult_m1, conjugate_m1, transpose_m1, adjunct_m1)


## Checking the Dimension of a Matrix
We can check the dimension of a matrix using the `.shape` attribute.

In [ ]:
# Checking the dimension of matrix1
m1.shape

## Action of a Matrix on a Vector
Finally, examples of how to use Python to multiply a 3x3 square matrix by a 3x1 column vector.

In [ ]:

# Multiplying a 3x3 matrix by a 3x1 vector
result = np.dot(m1, v1)
result


# Exercises on Complex Vectors and Matrices with Concrete Cases

This set of exercises focuses on operations with complex column vectors and complex square matrices, including concrete cases with vectors and matrices written in LaTeX format.

## Complex Column Vector Operations

### Exercise 1: Sum of Two Complex Vectors
Given two complex vectors 
$$ v1 = \begin{bmatrix} 1 + 2i \\ 3 - i \end{bmatrix} $$ 
and 
$$ v2 = \begin{bmatrix} 2 - i \\ 4 + 2i \end{bmatrix} $$, 
find their sum.

### Exercise 2: Negation of a Complex Vector
Given a complex vector 
$$ v = \begin{bmatrix} 2 + 3i \\ 1 - 2i \end{bmatrix} $$, 
find its negation.

### Exercise 3: Multiplication of a Complex Vector by a Scalar
Multiply the complex vector 
$$ v = \begin{bmatrix} 1 - i \\ 2 + 2i \end{bmatrix} $$ 
by the complex scalar $$ 3 + i $$.

### Exercise 4: Transpose of a Complex Vector
Find the transpose of the complex vector 
$$ v = \begin{bmatrix} 2 - i \\ 3 + 4i \end{bmatrix} $$.

### Exercise 5: Conjugate of a Complex Vector
Compute the conjugate of the complex vector 
$$ v = \begin{bmatrix} 1 + i \\ 2 - 3i \end{bmatrix} $$.

### Exercise 6: Adjunct (Conjugate Transpose) of a Complex Vector
Find the adjunct (or conjugate transpose) of the complex vector 
$$ v = \begin{bmatrix} 1 - 2i \\ 3 + i \end{bmatrix} $$.

## Complex Square Matrix Operations

### Exercise 7: Sum of Two Complex Matrices
Given two complex matrices 
$$ m1 = \begin{bmatrix} 1 + i & 2 - i \\ 3 + 2i & 4 \end{bmatrix} $$ 
and 
$$ m2 = \begin{bmatrix} 2 - 3i & 1 \\ i & 2 + 2i \end{bmatrix} $$, 
calculate their sum.

### Exercise 8: Negation of a Complex Matrix
Find the negation of the complex matrix 
$$ m = \begin{bmatrix} 2 + i & 3 \\ 1 - i & 2 + 2i \end{bmatrix} $$.

### Exercise 9: Multiplication of a Complex Matrix by a Scalar
Multiply the complex matrix 
$$ m = \begin{bmatrix} 1 - i & 2 \\ 3 + i & 4 - 2i \end{bmatrix} $$ 
by the complex scalar $$ 2 + 3i $$.

### Exercise 10: Conjugate of a Complex Matrix
Compute the conjugate of the complex matrix 
$$ m = \begin{bmatrix} 1 + i & 2 \\ 3 - i & 4 + 2i \end{bmatrix} $$.

### Exercise 11: Transpose of a Complex Matrix
Find the transpose of the complex matrix 
$$ m = \begin{bmatrix} 1 - i & 2 + 2i \\ 3 & 4 - i \end{bmatrix} $$.

### Exercise 12: Adjunct (Conjugate Transpose) of a Complex Matrix
Calculate the adjunct (or conjugate transpose) of the complex matrix 
$$ m = \begin{bmatrix} 1 + 2i & 3 - i \\ 4 & 5 + i \end{bmatrix} $$.

### Exercise 13: Checking the Dimensions of a Matrix
Determine the dimensions of the complex matrix 
$$ m = \begin{bmatrix} 1 - i & 2 \\ 3 + 2i & 4 - i \end{bmatrix} $$.

## Multiplication of Matrices and Vectors

### Exercise 14: Multiplying a Complex Square Matrix by a Complex Column Vector
Multiply the complex square matrix 
$$ m = \begin{bmatrix} 1 + i & 2 - i \\ 3 & 4 + i \end{bmatrix} $$ 
by the complex column vector 
$$ v = \begin{bmatrix} 2 - i \\ 1 + 3i \end{bmatrix} $$.

## Instructions
For each exercise, ensure to display both the input (vectors/matrices) and the result of the operation.Use NumPy for these exercises to practice handling complex numbers and matrix operations in Python.




#respuestas 
### Exercise 1: Sum of Two Complex Vectors
Given two complex vectors 
$$ v1 = \begin{bmatrix} 1 + 2i \\ 3 - i \end{bmatrix} $$ 
and 
$$ v2 = \begin{bmatrix} 2 - i \\ 4 + 2i \end{bmatrix} $$, 
find their sum.
### solucion

In [9]:
# Define two complex column vectors
v1 = np.array([[1+2j],[3-1j]])
v2 = np.array([[2-1j],[4+2j]])

print("vectores a sumar")
print("")
print("v1 = ", v1)
print("v2 = ", v2)
print("")
print("suma")
suma = v1 + v2
print("v1 + v2 = ", suma)

vectores a sumar

v1 =  [[1.+2.j]
 [3.-1.j]]
v2 =  [[2.-1.j]
 [4.+2.j]]

suma
v1 + v2 =  [[3.+1.j]
 [7.+1.j]]


### Exercise 2: Negation of a Complex Vector
Given a complex vector 
$$ v = \begin{bmatrix} 2 + 3i \\ 1 - 2i \end{bmatrix} $$, 
find its negation.

### solucion

In [13]:
#define negation of a vector
v1 = np.array([[2+3j],[1-2j]])

print("vector")
print("v1 = " , v1)

print("negative")
print("-v1 = " , -v1)

vector
v1 =  [[2.+3.j]
 [1.-2.j]]
negative
-v1 =  [[-2.-3.j]
 [-1.+2.j]]


### Exercise 3: Multiplication of a Complex Vector by a Scalar
Multiply the complex vector 
$$ v = \begin{bmatrix} 1 - i \\ 2 + 2i \end{bmatrix} $$ 
by the complex scalar $$ 3 + i $$.
### Solution



In [19]:
### multiply the vector whit scalar

print("vector and scalar")
print("")
v1 =  np.array([[1-1j],[2+2j]])
c1 = [3+1j]

print("v1 = " , v1)
print("c1 = " , c1)

M1 = c1 * v1

print("")
print("multiply")
print("")
print("c1 * v1 = " , M1)

vector and scalar

v1 =  [[1.-1.j]
 [2.+2.j]]
c1 =  [(3+1j)]

multiply

c1 * v1 =  [[4.-2.j]
 [4.+8.j]]


### Exercise 4: Transpose of a Complex Vector
Find the transpose of the complex vector 
$$ v = \begin{bmatrix} 2 - i \\ 3 + 4i \end{bmatrix} $$.
### Solution

In [20]:
print("vector and scalar")
print("")
v1 =  np.array([[2-1j],[3+4j]])

print("v1 = " , v1)

traspose = v1.T

print("traspose = " , traspose)



vector and scalar

v1 =  [[2.-1.j]
 [3.+4.j]]
traspose =  [[2.-1.j 3.+4.j]]


### Exercise 5: Conjugate of a Complex Vector
Compute the conjugate of the complex vector 
$$ v = \begin{bmatrix} 1 + i \\ 2 - 3i \end{bmatrix} $$.
### Solution

In [22]:
print("vector and scalar")
print("")
v1 =  np.array([[1+1j],[2-3j]])

print("v1 = " , v1)

conjugate = v1.T.conj()

print("conjugate = " , conjugate)

vector and scalar

v1 =  [[1.+1.j]
 [2.-3.j]]
conjugate =  [[1.-1.j 2.+3.j]]


### Exercise 6: Adjunct (Conjugate Transpose) of a Complex Vector
Find the adjunct (or conjugate transpose) of the complex vector 
$$ v = \begin{bmatrix} 1 - 2i \\ 3 + i \end{bmatrix} $$.
### solution

### Exercise 7: Sum of Two Complex Matrices
Given two complex matrices 
$$ m1 = \begin{bmatrix} 1 + i & 2 - i \\ 3 + 2i & 4 \end{bmatrix} $$ 
and 
$$ m2 = \begin{bmatrix} 2 - 3i & 1 \\ i & 2 + 2i \end{bmatrix} $$, 
calculate their sum.
### solution

In [29]:
print("matrices")
print("")
m1 = np.array([[1+1j, 2-1j], 
               [3+2j, 4]])

m2 = np.array([[2-3j, 1], 
               [1j, 2+2j]])

print("")
print("m1 = " , m1)
print("m2 = " , m2)
print("")
suma = m1 + m2
print("suma")
print("m1 + m2 = " , suma)

matrices


m1 =  [[1.+1.j 2.-1.j]
 [3.+2.j 4.+0.j]]
m2 =  [[2.-3.j 1.+0.j]
 [0.+1.j 2.+2.j]]

suma
m1 + m2 =  [[3.-2.j 3.-1.j]
 [3.+3.j 6.+2.j]]


### Exercise 8: Negation of a Complex Matrix
Find the negation of the complex matrix 
$$ m = \begin{bmatrix} 2 + i & 3 \\ 1 - i & 2 + 2i \end{bmatrix} $$.
### solution

In [30]:
print("matris")
print("")
m1 = np.array([[1+1j, 2-1j], 
               [3+2j, 4]])

print("")
print("m1 = " , m1)
print("")
negacion = -m1
print("negacion")
print("-m1 = " , negacion)

matris


m1 =  [[1.+1.j 2.-1.j]
 [3.+2.j 4.+0.j]]

negacion
-m1 =  [[-1.-1.j -2.+1.j]
 [-3.-2.j -4.-0.j]]


### Exercise 9: Multiplication of a Complex Matrix by a Scalar
Multiply the complex matrix 
$$ m = \begin{bmatrix} 1 - i & 2 \\ 3 + i & 4 - 2i \end{bmatrix} $$ 
by the complex scalar $$ 2 + 3i $$.
### solution


In [37]:
print("matris and scalar")
print("")
m1 = np.array([[1-1j, 2], 
               [3+1j, 4-2j]])

c1 = 2+3j

print("")
print("m1 = " , m1)
print("c1 = " , c1)
print("")
producto = m1*c1
print("multiplicacion por escalar")
print("m1 * c1 = " , producto)

matris and scalar


m1 =  [[1.-1.j 2.+0.j]
 [3.+1.j 4.-2.j]]
c1 =  (2+3j)

multiplicacion por escalar
m1 * c1 =  [[ 5. +1.j  4. +6.j]
 [ 3.+11.j 14. +8.j]]


### Exercise 10: Conjugate of a Complex Matrix
Compute the conjugate of the complex matrix 
$$ m = \begin{bmatrix} 1 + i & 2 \\ 3 - i & 4 + 2i \end{bmatrix} $$.
### solution

In [38]:
print("conjugate")
print("")
m1 = np.array([[1+1j, 2], 
               [3-1j, 4+2j]])

print("")
print("m1 = " , m1)
print("")
conjugado = np.conjugate(m1)
print("conjugado")
print("conjugado m1 = " , conjugado)

conjugate


m1 =  [[1.+1.j 2.+0.j]
 [3.-1.j 4.+2.j]]

conjugado
conjugado m1 =  [[1.-1.j 2.-0.j]
 [3.+1.j 4.-2.j]]


### Exercise 11: Transpose of a Complex Matrix
Find the transpose of the complex matrix 
$$ m = \begin{bmatrix} 1 - i & 2 + 2i \\ 3 & 4 - i \end{bmatrix} $$.
### solution

In [39]:
print("transpuesta")
print("")
m1 = np.array([[1-1j, 2+2j], 
               [3, 4-1j]])

print("")
print("m1 = " , m1)
print("")
transpuesta = m1.T
print("transpuesta")
print("transpuesta m1 = " , transpuesta)

transpuesta


m1 =  [[1.-1.j 2.+2.j]
 [3.+0.j 4.-1.j]]

transpuesta
transpuesta m1 =  [[1.-1.j 3.+0.j]
 [2.+2.j 4.-1.j]]


### Exercise 12: Adjunct (Conjugate Transpose) of a Complex Matrix
Calculate the adjunct (or conjugate transpose) of the complex matrix 
$$ m = \begin{bmatrix} 1 + 2i & 3 - i \\ 4 & 5 + i \end{bmatrix} $$.
### solution

### Exercise 13: Checking the Dimensions of a Matrix
Determine the dimensions of the complex matrix 
$$ m = \begin{bmatrix} 1 - i & 2 \\ 3 + 2i & 4 - i \end{bmatrix} $$.
### solution

## Multiplication of Matrices and Vectors

### Exercise 14: Multiplying a Complex Square Matrix by a Complex Column Vector
Multiply the complex square matrix 
$$ m = \begin{bmatrix} 1 + i & 2 - i \\ 3 & 4 + i \end{bmatrix} $$ 
by the complex column vector 
$$ v = \begin{bmatrix} 2 - i \\ 1 + 3i \end{bmatrix} $$.
### solution